version: '3'

services:

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb

  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_port=27017
    ports:
      - 8000:8000
    links:
      - mongodb

